trigger:
  # Trigger for pushes on every branch
  branches:
    include:
    - '*'

  # Trigger for all tags
  tags:
    include:
    - '*'

pr:
  # Cancel if new commits are pushed to the same PR
  autoCancel: true

  # Trigger for PRs on all branches
  branches:
    include:
    - '*'

variables:
  # Read deployment variables from our secret group
  - group: deploy-vars
  - name: PIP_CACHE_DIRECTORY
    value: $(Pipeline.Workspace)/.pip

jobs:
- template: build_tools/azure/jobs.yml
