jobs:
- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    maxParallel: 6
    matrix:
      Python35-x86:
        python.version: '3.5'
        architecture: 'x86'

      Python35-x64:
        python.version: '3.5'
        architecture: 'x64'

      Python36-x86:
        python.version: '3.6'
        architecture: 'x86'

      Python36-x64:
        python.version: '3.6'
        architecture: 'x64'

      Python37-x86:
        python.version: '3.7'
        architecture: 'x86'

      Python37-x64:
        python.version: '3.7'
        architecture: 'x64'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(architecture)'
    displayName: 'Setting Python version and system architecture'

  # We do this outside of the template, because only Windows uses architecture
  - task: CacheBeta@0
    inputs:
      key: |
        $(Agent.OS)
        $(python.version)
        $(architecture)
        $(Build.SourcesDirectory)/requirements.txt
        $(Build.SourcesDirectory)/build_tools/azure/requirements.txt
      path: c:\hostedtoolcache\windows\python\$(python.version)\$(architecture)\lib\site-packages
      cacheHitVar: CACHE_RESTORED
    displayName: Cache packages

  - template: build_and_deploy.yml

- job: macOS

  pool:
    vmImage: 'macOS-10.13'  # Also have the option of 10.14, if we want that

  # Only need to set this for macOS
  variables:
    PMD_MPL_BACKEND: TkAgg

  strategy:
    maxParallel: 3
    matrix:
      Python35:
        python.version: '3.5'

      Python36:
        python.version: '3.6'

      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Setting Python version'

  # We do this outside of the template, because macOS does not use architecture variable
  - task: CacheBeta@0
    inputs:
      key: |
        $(Agent.OS)
        $(python.version)
        $(Build.SourcesDirectory)/requirements.txt
        $(Build.SourcesDirectory)/build_tools/azure/requirements.txt
      path: /Users/vsts/hostedtoolcache/Python/$(python.version)/x86/$[ substring($(python.version), 0, 3) ]/site-packages
      cacheHitVar: CACHE_RESTORED
    displayName: Cache packages

  - template: build_and_deploy.yml
